[32m2025-05-28 14:02:19 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - 3771 - LOGS_CAPTURED - Started capturing logs in process (pid: 3771).
[32m2025-05-28 14:02:19 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - 3771 - dbt_analytics - STEP_START - Started execution of step "dbt_analytics".
[32m2025-05-28 14:02:19 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['analytics.dim.dim_agent', 'analytics.dim.dim_address', 'analytics.dim.dim_agency']`.
INFO:dagster.builtin:__ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['analytics.dim.dim_agent', 'analytics.dim.dim_address', 'analytics.dim.dim_agency']`.
[32m2025-05-28 14:02:19 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - Copying `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/partial_parse.msgpack` to `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/dbt_analytics-cb643da-3da756f/partial_parse.msgpack` to take advantage of partial parsing.
INFO:dagster.builtin:__ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - Copying `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/partial_parse.msgpack` to `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/dbt_analytics-cb643da-3da756f/partial_parse.msgpack` to take advantage of partial parsing.
[32m2025-05-28 14:02:19 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - Running dbt command: `dbt build --select analytics.dim.dim_agent analytics.dim.dim_address analytics.dim.dim_agency`.
INFO:dagster.builtin:__ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - Running dbt command: `dbt build --select analytics.dim.dim_agent analytics.dim.dim_address analytics.dim.dim_agency`.
[32m2025-05-28 14:02:21 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - Finished dbt command: `dbt build --select analytics.dim.dim_agent analytics.dim.dim_address analytics.dim.dim_agency`.
INFO:dagster.builtin:__ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - dbt_analytics - Finished dbt command: `dbt build --select analytics.dim.dim_agent analytics.dim.dim_address analytics.dim.dim_agency`.
[32m2025-05-28 14:02:21 +1000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - cb643da3-7d5f-45b0-825a-f30e7ffc9add - 3771 - dbt_analytics - STEP_FAILURE - Execution of step "dbt_analytics" failed.

dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command

`dbt build --select analytics.dim.dim_agent analytics.dim.dim_address analytics.dim.dim_agency`

failed with exit code `1`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/dbt_analytics-cb643da-3da756f/dbt.log.

Errors parsed from dbt logs:

1 of 3 ERROR creating sql table model main.dim_address ......................... [[31mERROR[0m in 0.03s]

2 of 3 ERROR creating sql table model main.dim_agency .......................... [[31mERROR[0m in 0.01s]

3 of 3 ERROR creating sql table model main.dim_agent ........................... [[31mERROR[0m in 0.01s]

  Runtime Error in model dim_address (models/dim/dim_address.sql)
  Catalog Error: Table with name stg_addresses does not exist!
  Did you mean "realestate.stg_addresses"?
  
  LINE 12:     SELECT * FROM "realestate"."main_public"."stg_addresses"
                             ^

  Runtime Error in model dim_agency (models/dim/dim_agency.sql)
  Catalog Error: Table with name stg_agencies does not exist!
  Did you mean "realestate.stg_agencies"?
  
  LINE 12:     SELECT * FROM "realestate"."main_public"."stg_agencies"
                             ^

  Runtime Error in model dim_agent (models/dim/dim_agent.sql)
  Catalog Error: Table with name stg_agents does not exist!
  Did you mean "realestate.stg_agents"?
  
  LINE 12:     SELECT * FROM "realestate"."main_public"."stg_agents" WHERE email != ''
                             ^

Stack Trace:
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 507, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 190, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 89, in _process_asset_results_to_events
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 187, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 156, in _yield_compute_results
    for event in iterate_with_context(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/dagster_university/assets/dbt.py", line 38, in dbt_analytics
    yield from dbt.cli(["build"], context=context).stream()
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_event_iterator.py", line 206, in __next__
    return next(self._inner_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 276, in _stream_asset_events
    for event in self.stream_raw_events():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 368, in stream_raw_events
    self._raise_on_error()
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 461, in _raise_on_error
    raise error
[0m
