[32m2025-05-28 11:41:58 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - 49682 - LOGS_CAPTURED - Started capturing logs in process (pid: 49682).
[32m2025-05-28 11:41:58 +1000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - 49682 - dbt_analytics - STEP_START - Started execution of step "dbt_analytics".
[32m2025-05-28 11:41:58 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['analytics.dim.dim_date']`.
INFO:dagster.builtin:__ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['analytics.dim.dim_date']`.
[32m2025-05-28 11:41:58 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - Copying `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/partial_parse.msgpack` to `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/dbt_analytics-c6a4202-d385c72/partial_parse.msgpack` to take advantage of partial parsing.
INFO:dagster.builtin:__ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - Copying `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/partial_parse.msgpack` to `/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/dbt_analytics-c6a4202-d385c72/partial_parse.msgpack` to take advantage of partial parsing.
[32m2025-05-28 11:41:58 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - Running dbt command: `dbt build --select analytics.dim.dim_date`.
INFO:dagster.builtin:__ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - Running dbt command: `dbt build --select analytics.dim.dim_date`.
[32m2025-05-28 11:41:59 +1000[0m - dagster - [34mINFO[0m - __ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - Finished dbt command: `dbt build --select analytics.dim.dim_date`.
INFO:dagster.builtin:__ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - dbt_analytics - Finished dbt command: `dbt build --select analytics.dim.dim_date`.
[32m2025-05-28 11:41:59 +1000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - c6a42022-2d9e-4b8e-8c0e-1167dd4998ab - 49682 - dbt_analytics - STEP_FAILURE - Execution of step "dbt_analytics" failed.

dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command

`dbt build --select analytics.dim.dim_date`

failed with exit code `1`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/analytics/target/dbt_analytics-c6a4202-d385c72/dbt.log.

Errors parsed from dbt logs:

1 of 1 ERROR creating sql table model main.dim_date ............................ [[31mERROR[0m in 0.03s]

  Runtime Error in model dim_date (models/dim/dim_date.sql)
  Binder Error: Referenced column "listing_id" not found in FROM clause!
  Candidate bindings: "list_sold_date"
  
  LINE 15:     listing_id,
               ^

Stack Trace:
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 507, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 190, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 89, in _process_asset_results_to_events
    for user_event in user_event_sequence:
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 187, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 156, in _yield_compute_results
    for event in iterate_with_context(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/dagster_university/assets/dbt.py", line 38, in dbt_analytics
    yield from dbt.cli(["build"], context=context).stream()
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_event_iterator.py", line 206, in __next__
    return next(self._inner_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 276, in _stream_asset_events
    for event in self.stream_raw_events():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 368, in stream_raw_events
    self._raise_on_error()
  File "/Users/jacktoke/Codes/DataEngineer/LeWagon/project_du_dbt_starter/.venv/lib/python3.12/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 461, in _raise_on_error
    raise error
[0m
